# Generated by Django 5.1.2 on 2024-10-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="updated_at",
        ),
    ]
