# Generated by Django 5.1.2 on 2024-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="store.category", verbose_name="კატეგორიები"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to="products/", verbose_name="სურათი"
            ),
        ),
    ]
