# Generated by Django 5.1.2 on 2024-10-10 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_productcategory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
