# Generated by Django 5.1.2 on 2024-10-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_categories_alter_product_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("product", "category")},
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="updated_at",
        ),
    ]
