# Generated by Django 5.1.2 on 2024-10-11 05:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_productcategory_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="store.category", verbose_name="კატეგორიები"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="store.category",
                verbose_name="მშობელი კატეგორია",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="სურათი"
            ),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
