# Generated by Django 5.1.2 on 2024-10-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_categories_alter_category_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="რაოდენობა"),
        ),
    ]
