# Generated by Django 5.1.2 on 2024-10-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_productcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together=set(),
        ),
    ]
